---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "rg-test-api-config-8dx2"
  namespace: "default"
  labels:
    app: "rg-test-api"
data:
  HOST: "0.0.0.0"
  PORT: "80"
  REDIS_HOST: "10.41.127.179"
  REDIS_PORT: "6379"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "rg-test-api"
  namespace: "default"
  labels:
    app: "rg-test-api"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "rg-test-api"
  template:
    metadata:
      labels:
        app: "rg-test-api"
    spec:
      containers:
      - name: "api-sha256-1"
        image: "gcr.io/sandbox-314159/rg-test/api@sha256:3031eb96819665f794ddce3f205e78ff7537efca69f8a9693de25bb24e7bda71"
        env:
        - name: "HOST"
          valueFrom:
            configMapKeyRef:
              key: "HOST"
              name: "rg-test-api-config-8dx2"
        - name: "PORT"
          valueFrom:
            configMapKeyRef:
              key: "PORT"
              name: "rg-test-api-config-8dx2"
        - name: "REDIS_HOST"
          valueFrom:
            configMapKeyRef:
              key: "REDIS_HOST"
              name: "rg-test-api-config-8dx2"
        - name: "REDIS_PORT"
          valueFrom:
            configMapKeyRef:
              key: "REDIS_PORT"
              name: "rg-test-api-config-8dx2"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "rg-test-api-hpa-ctxe"
  namespace: "default"
  labels:
    app: "rg-test-api"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "rg-test-api"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

