version: "3.9"
services:
  redis:
    image: "redis:alpine"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/opt
    env_file:
      - .env
    ports:
      - "5000:5000"
