apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-05-31T15:28:20Z"
  generation: 1
  labels:
    app: rg-test-api
  name: rg-test-api
  namespace: default
  resourceVersion: "16243"
  selfLink: /apis/apps/v1/namespaces/default/deployments/rg-test-api
  uid: fbcd2982-eb6f-43fa-9212-0dc4da3c9d02
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rg-test-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rg-test-api
    spec:
      containers:
      - env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              key: REDIS_HOST
              name: rg-test-api-config-ugav
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              key: REDIS_PORT
              name: rg-test-api-config-ugav
        - name: HOST
          valueFrom:
            configMapKeyRef:
              key: HOST
              name: rg-test-api-config-ugav
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: PORT
              name: rg-test-api-config-ugav
        image: gcr.io/sandbox-314159/github.com/darthgoon/rg-test@sha256:ad17c3cc341e0cc4a9728d73e1ada7a5725d480eed2c353d50a5bc178d10cd17
        imagePullPolicy: IfNotPresent
        name: rg-test-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2021-05-31T15:28:22Z"
    lastUpdateTime: "2021-05-31T15:28:22Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-05-31T15:28:20Z"
    lastUpdateTime: "2021-05-31T15:28:22Z"
    message: ReplicaSet "rg-test-api-856b9b754" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
