---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "rg-test-api-config-qf4p"
  namespace: "default"
  labels:
    app: "rg-test-api"
data:
  HOST: "0.0.0.0"
  PORT: "5000"
  REDIS_HOST: "10.63.160.3"
  REDIS_PORT: "6379"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "rg-test-api"
  namespace: "default"
  labels:
    app: "rg-test-api"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "rg-test-api"
  template:
    metadata:
      labels:
        app: "rg-test-api"
    spec:
      containers:
      - name: "rg-test-sha256-1"
        image: "gcr.io/sandbox-314159/github.com/darthgoon/rg-test@sha256:0ada665f32e86121c193d716408f496c891ff34a82d417e0ffa79842d1080007"
        env:
        - name: "HOST"
          valueFrom:
            configMapKeyRef:
              key: "HOST"
              name: "rg-test-api-config-qf4p"
        - name: "PORT"
          valueFrom:
            configMapKeyRef:
              key: "PORT"
              name: "rg-test-api-config-qf4p"
        - name: "REDIS_HOST"
          valueFrom:
            configMapKeyRef:
              key: "REDIS_HOST"
              name: "rg-test-api-config-qf4p"
        - name: "REDIS_PORT"
          valueFrom:
            configMapKeyRef:
              key: "REDIS_PORT"
              name: "rg-test-api-config-qf4p"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "rg-test-api-hpa-tkyr"
  namespace: "default"
  labels:
    app: "rg-test-api"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "rg-test-api"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

