---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "rg-test-api-config-fmbf"
  namespace: "default"
  labels:
    app: "rg-test-api"
data:
  REDIS_HOST: "10.63.160.3"
  REDIS_PORT: "6379"
  HOST: "0.0.0.0"
  PORT: "5000"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "rg-test-api"
  namespace: "default"
  labels:
    app: "rg-test-api"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "rg-test-api"
  template:
    metadata:
      labels:
        app: "rg-test-api"
    spec:
      containers:
      - name: "rg-test-sha256-1"
        image: "gcr.io/sandbox-314159/github.com/darthgoon/rg-test@sha256:ad17c3cc341e0cc4a9728d73e1ada7a5725d480eed2c353d50a5bc178d10cd17"
        env:
        - name: "REDIS_HOST"
          valueFrom:
            configMapKeyRef:
              key: "REDIS_HOST"
              name: "rg-test-api-config-fmbf"
        - name: "REDIS_PORT"
          valueFrom:
            configMapKeyRef:
              key: "REDIS_PORT"
              name: "rg-test-api-config-fmbf"
        - name: "HOST"
          valueFrom:
            configMapKeyRef:
              key: "HOST"
              name: "rg-test-api-config-fmbf"
        - name: "PORT"
          valueFrom:
            configMapKeyRef:
              key: "PORT"
              name: "rg-test-api-config-fmbf"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "rg-test-api-hpa-bubk"
  namespace: "default"
  labels:
    app: "rg-test-api"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "rg-test-api"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

