---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "rg-test-api-service"
  namespace: "default"
  labels:
    app: "rg-test-api"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: "rg-test-api"
  type: "LoadBalancer"
  loadBalancerIP: ""

