apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2021-05-31T14:47:46Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  generateName: rg-test-api-
  labels:
    app: rg-test-api
  name: rg-test-api-fwhzz
  namespace: default
  resourceVersion: "1773"
  selfLink: /api/v1/namespaces/default/services/rg-test-api-fwhzz
  uid: fd6da2a8-7ef4-4091-ac94-e8cee11f5d32
spec:
  clusterIP: 10.48.12.213
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31486
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: rg-test-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 104.198.241.162
